# Generated by Django 4.2.16 on 2026-07-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
