# Generated by Django 4.2.16 on 2026-07-10 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_exam_scheduled_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamattempt',
            options={},
        ),
        migrations.RenameField(
            model_name='studentexamattempt',
            old_name='started_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='time_taken_minutes',
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('passed', 'Passed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
